### ISSUE TITLE
buildRouteArn should be made a static function of AuthResponse class

### ISSUE THREAD

**Issue by KillDozerX2** [distinction-dev/lambda-authorizer-utils#8]
## Current Behavior
Currently buildRouteArn is an exported function that can be used to build arn for a route, with the new PR #7 and it cleaning `/` at the end, it just doesn't make sense to make it available outside the AuthResponse class.

## Expected Behavior
We should make it a static member of the AuthResponse class.

**Comment by notanmay** [comment]
closed by #11
